### ISSUE TITLE
Install to MacOS

### ISSUE THREAD

**Issue by Diaglyonok** [IlyaSkriblovsky/hid-xiaomi#1]
Hi, do you know how to install your solution to MacOS? /usr/share folder is locked by SIP, i can not unpack(dpkg) your deb package. Maybe there is a way to manually install (or compile code) to MacOS?

**Comment by Diaglyonok** [comment]
closed, because of linux includes in .c file. If you know the way how to adapt your code to MacOS, please tell me how to do it.

**Comment by IlyaSkriblovsky** [comment]
No way, Oleg, this driver is certainly linux-specific :(
